### PR TITLE
two bug.

### PR DESCRIPTION
**Pull request by liguojiang**

### CODE REVIEW

**Comment by liguojiang** [comment]
1、radius.c
when Framed-IP-Address return from radius server, Accel-pppd call get_ipv4 from ippool.c instead of radius.c

2、packet.c
when some radius server return error radius packet, Accel-pppd will crash.

**Comment by liguojiang** [comment]
xebd, I have found two bug, please check it.

**Comment by liguojiang** [comment]
DEFINE_INIT(50, radius_init);

**Comment by liguojiang** [comment]
radius.c

DEFINE_INIT(50, radius_init);

**Comment by xebd** [comment]
Thanks.
But I can only accept 9307f56.
If you want to use radius for IP allocation then place radius above ippool
[modules]
radius
ippool

**Comment by liguojiang** [comment]
OK

**Pull request closed without merging**
